// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

XYLOMODULARSPELLS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_XMS_NodeIdentifier_Node)
XYLOMODULARSPELLS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_XMS_NodeIdentifier_InstructionNode)
XYLOMODULARSPELLS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_XMS_NodeIdentifier_StringProvider)
XYLOMODULARSPELLS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_XMS_NodeIdentifier_IntegerProvider)

